services:
  web:
    build:
      context: .
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - HOSTNAME=0.0.0.0
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    restart: unless-stopped
